# Generated by Django 3.2.25 on 2026-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
